<div class="jumbotron">
    <h1><span class="edms-blue">Bibliothèque edms</span></h1>

    <p>
        Edms,<br />
	La bibliothèque regroupe nos documentations papiers, documentations numérisées, références internet de fournisseurs, normes SIA et nos archives.<br />
	Vous pouvez réaliser vos recherches par catégories de documents ou types de documents.<br />
	Enfin sous « TOUS LES DOCUMENTS » vous réaliserez des recherches par mots clés. 
    </p>
</div>
