<?php

$title = 'Gestion des sections de la bibliothèque';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    Dans cette partie de l'application vous pourrez faire vos recherches par section de la bibliothéque.<br />
    Cliquez sur le nom de la section désirée pour lister les document de celle-ci.
</p>
<p>
    <a href="<?= $this->url('section', ['action' => 'add']) ?>"><button class="btn-lg btn-primary" type="button">Add new album</button></a>
    <a href="<?= $this->url('section', ['action' => 'add']) ?>"><button class="btn-lg btn-primary" type="button">Add new album</button></a>
    <a href="<?= $this->url('section', ['action' => 'add']) ?>"><button class="btn-lg btn-primary" type="button">Add new album</button></a>
    <a href="<?= $this->url('section', ['action' => 'add']) ?>"><button class="btn-lg btn-primary" type="button">Add new album</button></a>
</p>