<?php

$title = 'Gestion des sections de la bibliothèque';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    Dans cette partie de l'application vous pourrez faire vos recherches par section de la bibliothéque.<br />
    Cliquez sur le nom de la section désirée pour lister les document de celle-ci.
</p>
<p>
    <a class="btn btn-lg btn-primary" role="button" href="<?= $this->url('section', ['action' => 'add']) ?>">Section 1</a>
    <a class="btn btn-lg btn-primary" role="button" href="<?= $this->url('section', ['action' => 'add']) ?>">Section 2</a>
    <a class="btn btn-lg btn-primary" role="button" href="<?= $this->url('section', ['action' => 'add']) ?>">Section 3</a>
    <a class="btn btn-lg btn-primary" role="button" href="<?= $this->url('section', ['action' => 'add']) ?>">Section 4</a>
</p>