<?php

$title = 'Liste des sections';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('section', ['action' => 'add']) ?>">Créer une nouvelle section</a>
</p>

<table class="table">
<tr>
    <th>Nom de section</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($sections as $section) : ?>
    <tr>
        <td><?= $this->escapeHtml($section->nom) ?></td>
        <td>
            <a href="<?= $this->url('section', ['action' => 'edit', 'id' => $section->id]) ?>">Modifier</a>
            <a href="<?= $this->url('section', ['action' => 'archive', 'id' => $section->id]) ?>">Archiver</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>