<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
	<?= $this->headTitle('EDMS Biblio')->setSeparator(' - ')->setAutoEscape(false) ?>

	<?=
	    $this->headMeta()
	    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
	    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>

        <!-- Le styles -->
	<?=
	    $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
	    ->prependStylesheet($this->basePath('css/style.css'))
	    ->prependStylesheet('https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css')
//            ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css')
	    ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
	    ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
	?>

        <!-- Scripts -->
	<?=
	    $this->headScript()
	    ->prependFile($this->basePath('js/custom.js'))
	    ->prependFile('https://cdn.datatables.net/plug-ins/1.10.19/filtering/type-based/accent-neutralise.js')
	    ->prependFile('https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js')
	    ->prependFile('https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js')
	    ->prependFile($this->basePath('js/bootstrap.min.js'))
	    ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
	?>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/edms-logo.bmp') ?>" height="28" alt="edms logo"/>&nbsp;Bibliothèque
                    </a>
                </div>
                <div class="collapse navbar-collapse">
		    <?=
			$this->navigation('navigation')
			->menu()
			->setMinDepth(0)
			->setMaxDepth(0)
			->setUlClass('nav navbar-nav')
		    ?>
                </div>
            </div>
        </nav>
	<?php
	echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissible', 'alert-success'));
	echo $this->flashMessenger()->render('error', array('alert', 'alert-dismissible', 'alert-danger'));
	?>
        <div class="container">
	    <?=
		$this->navigation('navigation')
		->breadcrumbs()
		->setMinDepth(0)
		->setPartial('partial/breadcrumb')
	    ?>
	    <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2009 - <?= date('Y') ?> edms sa.</p>
            </footer>
        </div>
	<?= $this->inlineScript() ?>
    </body>
</html>
