<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Archiver une categorie';
$url   = $this->url('categorie', ['action' => 'archive', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Etes-vous sûr de vouloir archiver la categorie :
    "<?= $this->escapeHtml($categorie->nom) ?>" ?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $categorie->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Oui" />
    <input type="submit" class="btn btn-success" name="del" value="Non" />
</div>
</form>