<?php
$title = 'Liste des catégories';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('categorie', ['action' => 'add']) ?>">Créer une nouvelle catégorie</a>
</p>

<table class="table table-striped table-bordered" id="categoriesList">
    <thead>
	<tr>
	    <th>Nom de catégorie</th>
	    <th>&nbsp;</th>
	</tr>
    </thead>
    <tbody>
	<?php foreach ($categories as $categorie) : ?>
    	<tr>
	    <td><?= $this->escapeHtml($categorie->nom)?></td>
    	    <td>
		<a class="btn btn-primary" role="button" href="<?= $this->url('categorie', ['action' => 'edit', 'id' => $categorie->id]) ?>"><span class="glyphicon glyphicon-pencil"></span>&nbsp;Modifier</a>
		<a class="btn btn-danger" role="button" href="<?= $this->url('categorie', ['action' => 'archive', 'id' => $categorie->id]) ?>"><span class="glyphicon glyphicon-remove"></span>&nbsp;Archiver</a>
    	    </td>
    	</tr>
	<?php endforeach; ?>
    </tbody>
</table>